import { Vehicle } from "@/types";

export const MOCK_VEHICLES: Vehicle[] = [
  {
    id: "mock-1",
    brand_id: "porsche",
    brand: { id: "porsche", name: "Porsche" },
    model: "911 GT3 RS",
    year_fab: 2024,
    year_model: 2024,
    version: "Câmbio PDK de 7 velocidades · 525cv",
    price: 1850000,
    mileage: 0,
    color: "Branco Carrara",
    fuel: "Gasolina",
    transmission: "Automático",
    doors: 2,
    description: `O Porsche 911 GT3 RS é a expressão máxima do desempenho em pista. Com o motor de 4.0L aspirado de 525cv derivado do motorsport, cada componente foi projetado para entregar velocidade bruta sem compromissos.\n\nA caçamba traseira ativa gera downforce adaptável, enquanto a suspensão PASM Sport garante feedback cirúrgico em qualquer tipo de trajetória. Uma conquista de engenharia que se sente em casa tanto na pista de corrida quanto nas melhores estradas do mundo.`,
    optionals: ["Pacote Weissach,Bancos de baqueta em fibra de carbono,Rodas centrais douradas,Freios cerâmicos PCCB,Câmera traseira,Câmera dianteira,Sistema de som Burmester,Apple CarPlay,Cronômetro de pista digital"],
    status: "disponível",
    is_featured: true,
    accepts_proposal: false,
    seller_id: "default",
    slug: "porsche-911-gt3-rs-2024",
    photos: [
      { id: "p-1", vehicle_id: "mock-1", url: "https://images.unsplash.com/photo-1614200187524-dc4b892acf16?auto=format&fit=crop&q=80&w=1800", storage_path: "", order_index: 0 },
      { id: "p-2", vehicle_id: "mock-1", url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=1800", storage_path: "", order_index: 1 },
      { id: "p-3", vehicle_id: "mock-1", url: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&q=80&w=1800", storage_path: "", order_index: 2 },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-2",
    brand_id: "mercedes",
    brand: { id: "mercedes", name: "Mercedes-AMG" },
    model: "G 63 Edition 1",
    year_fab: 2023,
    year_model: 2024,
    version: "V8 Biturbo 585cv · Night Package",
    price: 1980000,
    mileage: 1200,
    color: "Obsidian Black Metallic",
    fuel: "Gasolina",
    transmission: "Automático",
    doors: 4,
    description: `O Mercedes-AMG G 63 Edition 1 é muito mais do que um SUV — é um ícone cultural sobre rodas. Seu motor V8 biturbo de 4.0L produz 585cv e 850Nm de torque, capazes de acelerar esta fortaleza de 2.5 toneladas de 0 a 100km/h em apenas 4,5 segundos.\n\nCom o Night Package exclusivo, detalhes negros foscos cobrem toda a carroceria, criando uma estética sombria que domina qualquer rua. Interior em couro Nappa com acabamentos em carbono e tela MBUX de última geração completam a experiência.`,
    optionals: ["Night Package,Teto solar panorâmico,Pacote AMG Night Package II,Sistema de som Burmester 3D,Rodas AMG 22 polegadas,Assistente de estacionamento 360°,Câmeras surround view,Bancos aquecidos e ventilados,Heads-up display"],
    status: "disponível",
    is_featured: true,
    accepts_proposal: true,
    seller_id: "default",
    slug: "mercedes-amg-g63-2024",
    photos: [
      { id: "m-1", vehicle_id: "mock-2", url: "https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&q=80&w=1800", storage_path: "", order_index: 0 },
      { id: "m-2", vehicle_id: "mock-2", url: "https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&q=80&w=1800", storage_path: "", order_index: 1 },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-3",
    brand_id: "lamborghini",
    brand: { id: "lamborghini", name: "Lamborghini" },
    model: "Huracán STO",
    year_fab: 2023,
    year_model: 2023,
    version: "V10 Aspirado 640cv · Super Trofeo Omologata",
    price: 4250000,
    mileage: 500,
    color: "Arancio Borealis",
    fuel: "Gasolina",
    transmission: "Automático",
    doors: 2,
    description: `O Lamborghini Huracán STO representa o ápice da engenharia italiana voltada ao desempenho em pista com uso nas estradas. A sigla STO (Super Trofeo Omologata) não é apenas um nome — é uma promessa de que 75% dos componentes são herdados diretamente do competitivo Supertrofeo.\n\nSeu motor V10 atmosférico de 5.2L grita ao produzir 640cv a 8.000 rpm. O capô dianteiro funciona como difusor aerodinâmico e o aerofólio traseiro fixo garante 420kg de apoio a 280 km/h. Uma escultura que respira fogo.`,
    optionals: ["Vernice Opaca (pintura fosca),Carbono Forgiato nos painéis laterais,Janelas em policarbonato leve,Sistema de escape Akrapovič em titânio,Tela TFT de alta resolução,Câmera de pista Lamborghini,Kit de manutenção Squadra Corse"],
    status: "disponível",
    is_featured: true,
    accepts_proposal: false,
    seller_id: "default",
    slug: "lamborghini-huracan-sto-2023",
    photos: [
      { id: "l-1", vehicle_id: "mock-3", url: "https://images.unsplash.com/photo-1471444928139-48c5bf5173f8?auto=format&fit=crop&q=80&w=1800", storage_path: "", order_index: 0 },
      { id: "l-2", vehicle_id: "mock-3", url: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&q=80&w=1800", storage_path: "", order_index: 1 },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-4",
    brand_id: "bmw",
    brand: { id: "bmw", name: "BMW" },
    model: "M4 Competition",
    year_fab: 2024,
    year_model: 2024,
    version: "xDrive · Track Edition · 530cv",
    price: 845000,
    mileage: 0,
    color: "Isle of Man Green",
    fuel: "Gasolina",
    transmission: "Automático",
    doors: 2,
    description: `O BMW M4 Competition xDrive Track Edition é a resposta germânica ao desejo por um coupê de alto desempenho que pode ser usado diariamente sem abrir mão de qualquer prazer de condução.\n\nSeu motor S58 de 3.0L twin-turbo produz 530cv e 650Nm de torque, distribuídos às 4 rodas pelo sistema xDrive de tração integral. O pacote Track Edition inclui suspensão M adaptativa ajustada em Nürburgring, bancos de baqueta M Carbon e o sistema M Drive Professional com dados de telemetria em tempo real.`,
    optionals: ["Pacote Carbon Package,Bancos M Carbon,Teto em fibra de carbono,Sistema de escape M Performance,Rodas M forjadas 20/21 polegadas,Freios compostos M,HUD com exibição de pista,Câmera de ação integrada,Apple CarPlay sem fio"],
    status: "disponível",
    is_featured: true,
    accepts_proposal: true,
    seller_id: "default",
    slug: "bmw-m4-competition-2024",
    photos: [
      { id: "b-1", vehicle_id: "mock-4", url: "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&q=80&w=1800", storage_path: "", order_index: 0 },
      { id: "b-2", vehicle_id: "mock-4", url: "https://images.unsplash.com/photo-1607853202273-797f1c22a38e?auto=format&fit=crop&q=80&w=1800", storage_path: "", order_index: 1 },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-5",
    brand_id: "audi",
    brand: { id: "audi", name: "Audi" },
    model: "RS6 Avant",
    year_fab: 2024,
    year_model: 2024,
    version: "Performance · 630cv · Teto Solar",
    price: 960000,
    mileage: 800,
    color: "Nardo Grey",
    fuel: "Gasolina",
    transmission: "Automático",
    doors: 4,
    description: `O Audi RS6 Avant Performance é o unicórnio do segmento premium: uma station wagon capaz de acelerar de 0-100 em 3,4 segundos enquanto acomoda confortavelmente cinco passageiros e suas bagagens com classe incomparável.\n\nO motor TFSI V8 twin-turbo de 4.0L foi reprogramado para entregar 630cv e 850Nm na versão Performance. A suspensão pneumática adaptativa RS mantém o carro a 18mm mais baixo em modo RS Individual para máxima dinâmica de condução.`,
    optionals: ["Bancos esportivos RS em couro Valcona,Matrix LED Ultra,Bang & Olufsen 3D Advanced,Pacote Preto Óptico,All-road air suspension,Quattro Sport Differential,Head-up display com AR,Assistente de faixa,Carregamento sem fio"],
    status: "disponível",
    is_featured: true,
    accepts_proposal: true,
    seller_id: "default",
    slug: "audi-rs6-avant-2024",
    photos: [
      { id: "a-1", vehicle_id: "mock-5", url: "https://images.unsplash.com/photo-1606152421802-db97b9c7a11b?auto=format&fit=crop&q=80&w=1800", storage_path: "", order_index: 0 },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "mock-6",
    brand_id: "ferrari",
    brand: { id: "ferrari", name: "Ferrari" },
    model: "Roma Spider",
    year_fab: 2024,
    year_model: 2024,
    version: "V8 Biturbo 620cv · Retractable Hard Top",
    price: 3850000,
    mileage: 0,
    color: "Rosso Portofino",
    fuel: "Gasolina",
    transmission: "Automático",
    doors: 2,
    description: `A Ferrari Roma Spider celebra a dolce vita italiana com a capota rígida retrátil que em apenas 13,5 segundos transforma o coupê em um spider de céu aberto. Projetada para os que apreciam o belo tanto quanto o rápido.\n\nO motor V8 biturbo de 3.9L produz 620cv e 760Nm de torque. A transmissão F1-DCT de 8 velocidades realiza trocas em menos de 200 milissegundos, acompanhadas pelo uivo do escape que eleva a experiência sensorial a outro nível.`,
    optionals: ["Capota RHT em alumínio,Interior Alcantara Charcoal,Volante Manettino em carbono,Scuderie Ferrari Shields,Sistema Apple CarPlay,Freios de carbono-cerâmica,Rodas Tailor Made 20 polegadas,Câmera de visão dianteira"],
    status: "disponível",
    is_featured: false,
    accepts_proposal: false,
    seller_id: "default",
    slug: "ferrari-roma-spider-2024",
    photos: [
      { id: "f-1", vehicle_id: "mock-6", url: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?auto=format&fit=crop&q=80&w=1800", storage_path: "", order_index: 0 },
    ],
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export function getMockVehicleBySlug(slug: string): Vehicle | undefined {
  return MOCK_VEHICLES.find((v) => v.slug === slug);
}
